### ISSUE TITLE
Step Information should show  Module Name - step # - (text on first line of button if button is on step) - FIX

### ISSUE THREAD

**Issue by why-science** [why-science/demo#38]
Step Information should show  Module Name - step # - (text on first line of button if button is on step) - FIX

![image](https://user-images.githubusercontent.com/70287522/174859635-bbaa6d8e-1376-49b1-b500-60e8b28cfb5d.png)

For example for Step 2 show

"Restoring Holiness - Step 2 - Do I trust God?"
![image](https://user-images.githubusercontent.com/70287522/174868067-99e5da03-371d-4d54-838b-367556d04180.png)

For Step 3 of the module show

"Restoring Holiness - Step 3 - God is Holy"
![image](https://user-images.githubusercontent.com/70287522/174867989-94490a15-99fe-493c-bdcc-2aea638012e8.png)

**Comment by rajthilak87** [comment]
Do you want it for the button content alone or throughout the steps?

**Comment by rajthilak87** [comment]
Certain steps have "halfway", "Certificate" and "complete" should we change these formats.

1) step=1  ----> "modulename",
2) step=12 ----> "modulename --- Halfway",
3) step=23 ----> "modulename - Recap",
4) step=24 ----> "modulename - Complete",
5) step=25 ----> "modulename - Certificate",
6) (step='tools' or step='library' or $step='standards' or $step='rubrics' or $step='module-resources')  ----> "modulename - step name like Tools,Library,Standards,Rubrics,Module-Resources"
   module-step content contains button ----> "modulename - Step # -module step content first line",
7) otherwise ---->"modulename - Step #"

**Comment by why-science** [comment]
Implement the following:
Leave these as is
4. step=24 ----> "modulename - Complete" 
5. step=25 ----> "modulename - Certificate"

For everything else:
6. (step='tools' or step='library' or $step='standards' or $step='rubrics' or $step='module-resources') ----> "modulename - step name like Tools,Library,Standards,Rubrics,Module-Resources"
module-step content contains button ----> "modulename - Step # -module step content first line",
7. otherwise ---->"modulename - Step #"

Hope this feedback is helpful. Thanks

**Comment by rajthilak87** [comment]
Fixed

**Comment by why-science** [comment]
Thanks
